supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vitest: 4.1.11
  vite-plus: 0.3.2
  "@vitest/coverage-v8": 4.1.11
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
